### PR TITLE
Update domain/range of scenario properties.

### LINKED ISSUE #28: Possible updates to describesScenario property
proposal: 
1) remove domain from `gcis:describesScenario`
2) rename `gcis:isDescribedIn` to `gcis:scenarioDescribedIn`
2) remove range from `gcis:scenarioDescribedIn`
4) make `gcis:describesScenario` and `gcis:scenarioDescribedIn` inverse properties

### PR DESCRIPTION
**Pull request by zednis**
closes #28

### CODE REVIEW

**Comment by zednis** [comment]
Perhaps we should also update the comment on both properties?

**Comment by bduggan** [comment]
Yes, the comment should be updated too.

**Comment by zednis** [comment]
I have updated the property comments.

**Comment by justgo129** [comment]
Looks good to me.  @zedinis please merge.

**Pull request merged**
