### PR TITLE
Author report unit test

### PR DESCRIPTION
**Pull request by zednis**
references #113.  Added author report unit test.  I had to make modifications to the query because of incompatibilities in virtuoso and jena query syntax support.

@bduggan when I run ./run-tests.sh it shows the following for this test:

```
not ok 7 - 06-author-report.sparql
```

but a diff shows no difference between the expected results and the results in tmp

```
$ diff t/results/06-author-report.csv /tmp/06-author-report.csv 
```

### CODE REVIEW

**Comment by bduggan** [comment]
Looks okay now right?  At least travis is reporting that it is okay.  A possible cause could be line endings -- I recently changed "diff" to "diff -w" to account for this (so if you update to the latest code in the repo the test should pass).

**Comment by justgo129** [comment]
@bduggan may I merge?

**Comment by bduggan** [comment]
Yes, this looks good.

**Comment by justgo129** [comment]
Merged #155.

**Pull request merged**
