### PR TITLE
Observation system

### PR DESCRIPTION
**Pull request by xgmachina**
As an action to #104 
add a new class gcis:ObservationSystem to gcis ontology

### CODE REVIEW

**Comment by xgmachina** [comment]
@justgo129 could you take a review? thanks.

**Comment by justgo129** [comment]
Thanks, @xgmachina.  I'm not entirely sure I understand the meaning of a "sensing element."  Would it be possible to also relate gcis:Instrument somehow?  @rewolfe what do you think of the proposed definition?

**Comment by rewolfe** [comment]
This is a good definition.  We need to be able to connect one or more
platforms to the ObservationSystem.  For instance:

ObservationSystem: NOAA Polar Orbiting Environmental Platforms
(/observationsystem/noaa-poes)

Platforms: NOAA-1
(/platform/national-oceanic-and-atmospheric-administration-1), NOAA-2
(/platform/national-oceanic-and-atmospheric-administration-2), ..., NOAA-19
(/platform/national-oceanic-and-atmospheric-administration-19)

On Tue, Aug 18, 2015 at 6:40 PM, justgo129 notifications@github.com wrote:

> Thanks, @xgmachina https://github.com/xgmachina. I'm not entirely sure
> I understand the meaning of a "sensing element." Would it be possible to
> also relate gcis:Instrument somehow? @rewolfe https://github.com/rewolfe
> what do you think of the proposed definition?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/131#issuecomment-132377295.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
@rewolfe do you suggest further action be taken with regard to your comment, or do you feel that this is ready to be merged?

**Comment by rewolfe** [comment]
Shouldn't we also describe the relationship between platform and observing
system?   I think we need to define a "hasPlatform" relationship: a
ObservingSystem hasPlatform a Platform.  Perhaps the inverse is
"inObservingSystem".

On Thu, Aug 20, 2015 at 12:39 PM, justgo129 notifications@github.com
wrote:

> @rewolfe https://github.com/rewolfe do you suggest further action be
> taken with regard to your comment, or do you feel that this is ready to be
> merged?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/131#issuecomment-133070722.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by xgmachina** [comment]
@rewolfe  Perhaps add a general property `gcis:hasSensingElement` that can connect a observing system not only to platforms, but also to sensors, instruments, and even humans?

**Comment by rewolfe** [comment]
@xgmachina Yes, `gcis:hasSensingElements` a good idea.

**Comment by justgo129** [comment]
:+1: 1 to adding gcis:hasSensingElements

**Comment by justgo129** [comment]
@xgmachina please update the pull request accordingly.

**Comment by rewolfe** [comment]
+1 !

On Mon, Aug 24, 2015 at 2:10 PM, justgo129 notifications@github.com wrote:

> @xgmachina https://github.com/xgmachina please update the pull request
> accordingly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/131#issuecomment-134321557.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by xgmachina** [comment]
`gcis:hasSensingElement` was added as an object property. I will merge the pull request.

**Comment by justgo129** [comment]
Thanks, @xgmachina.

**Pull request merged**
