### PR TITLE
Added gcis:Indicator

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by justgo129** [comment]
@rewolfe I think this should work, although the rdfs:comment may cause someone to think that an indicator can be a non-published item (i.e., Indicators being the actual calculation or trend described in a report in-lieu of being one in its own right).  Is this good to merge?

**Comment by rewolfe** [comment]
@justgo129 This is a subclass of report (and therefore publication) so
there it is implicit that it is "an account".  Should we make this more
explicit in the definition: "Indicators are an account of ...".

One thing I find inconsistant is that some publicaiton subclasses are
subclasses of prov:Entity (e.g. gcis:Article) and some are not.

On Wed, Oct 14, 2015 at 9:44 AM, justgo129 notifications@github.com wrote:

> @rewolfe https://github.com/rewolfe I think this should work, although
> the rdfs:comment may cause someone to think that an indicator can be a
> non-published item (i.e., Indicators being the actual calculation or trend
> described in a report in-lieu of being one in its own right). Is this good
> to merge?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/161#issuecomment-148053857.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Good call, @rewolfe.  I just added "account of" to rdfs:comment:

rdfs:comment "Indicators are accounts of observations or calculations that can be used to track conditions and trends" .  

Merged #161.

I'm afraid I don't see the inconsistency for the other ones, as I see "prov:Entity" for reports, articles, books, journals, webpages, and reports.

**Comment by rewolfe** [comment]
@justgo129 So, should Indicators also be a sub-class of prov:Entity, or is
that implied?

On Wed, Oct 14, 2015 at 10:08 AM, justgo129 notifications@github.com
wrote:

> Merged #161 https://github.com/USGCRP/gcis-ontology/pull/161.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/161#event-435243781.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Yep, it's implied since Indicators are a sub-class of reports which are subclasses of prov:Entity.

**Pull request merged**
