### PR TITLE
Update run-tests.sh

### PR DESCRIPTION
**Pull request by zednis**
Changes to make to the ./run-tests.sh script invoked by Travis-CI
- [ ] update script to use test-specific data
- [x] update script to be compatible with OS/X

### CODE REVIEW

**Comment by zednis** [comment]
@justgo129 @rewolfe This is a pull request (not ready for merge) for the branch on which we can do updates to run-tests.sh

**Comment by justgo129** [comment]
Sounds good.  @zednis should we hold off on making changes to https://github.com/USGCRP/gcis-ontology/blob/master/gcis.ttl until after the tests are developed?

**Comment by rewolfe** [comment]
@justgo129 - Yes, hold off for now. -Robert

On Wed, Nov 4, 2015 at 8:54 AM, justgo129 notifications@github.com wrote:

> Sounds good. @zednis https://github.com/zednis should we hold off on
> making changes to
> https://github.com/USGCRP/gcis-ontology/blob/master/gcis.ttl until after
> the tests are developed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/170#issuecomment-153725019.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Understood.  Tabled #170.

**Comment by zednis** [comment]
@rewolfe Have the other updates to run-scripts.sh been implemented? If so, I think this pull request is ready to merge.

**Comment by rewolfe** [comment]
@zednis - I did a merge. I don't know why the results are not what l
expected.

**Comment by zednis** [comment]
OK.  Let's open a branch and discuss that.  I think this pull request is ready to merge though.  It's a one-liner right now that makes the diff call in run-tests.sh OS X compatible.  I'll merge.

**Comment by rewolfe** [comment]
Woops, I see that this was a different change. Merge was okay. @zednis

**Pull request merged**
