### PR TITLE
better jena url

### PR DESCRIPTION
**Pull request by bduggan**
Better Jena URL

### CODE REVIEW

**Comment by bduggan** [comment]
I need some help understanding this:

Error: Could not find or load main class riotcmd.riot

**Comment by zednis** [comment]
I should have asked this earlier, but why call that directory 't'?

**Comment by bduggan** [comment]
On Friday, July 31, Stephan Zednik wrote: 

> I should have asked this earlier, but why call that directory 't'?

't' for tests (this is the convention used by modules on CPAN).

**Comment by zednis** [comment]
OK, what we needed to do was build the sources from github to create the binary distribution .tar.gz and then install from that package in the same way we had been installing from the mirror.

It takes a long time to run the tests to build the binary distribution so I recommend that we build a binary distribution ourselves (I already did this locally) and host the binary distribution at a URL we control.  Then the install during Travis-CI will proceed the same way as it did before with the mirror.

@bduggan I will send you a temporary dropbox link to the binary distribution file via email.

**Comment by bduggan** [comment]
Thanks @zednis   Not exactly a 'binary distribution' but rather java byte code, right?  Too bad there isn't an ubuntu package for it.  Anyway, I think this is ready to merge.

**Comment by zednis** [comment]
@bduggan Can USGCRP host the file somewhere?  I do not want to use a Dropbox link.  If USGCRP cannot host the file, I may be able to host it from a TW server.

**Comment by bduggan** [comment]
An alternative technique would be to put the build process into
the travis file, then just add that as a cached directory in
the .travis.yml.

**Comment by bduggan** [comment]
Or even simpler would be to just use a mirror.  I don't like the idea of setting up our own mirror.
I think the reason this may have broken in the first place was that once 3.0.0 came out the previous version was unavailable.  Though now there seem to be issues with 3.0.0. and java..(which are on travis but don't happen on my local env...)

**Comment by zednis** [comment]
Jena 3.0 requires Java 8
The  Jena build process tests take 30 minutes to run.  I guess we could run the build process with tests skipped...

**Comment by bduggan** [comment]
I'm okay with the latest in this pull request: downloads the binary for version 3, and uses jdk version 8.  @zednis , okay with this being merged?

**Comment by zednis** [comment]
My only concern is what happens when/if the mirror disappears or that version is no longer hosted on the mirror?  I noticed that several mirrors didn't have 2.13 after 3.0 was released.

This update as it is should work for now but we might be right back at this problem at some point in the future.

**Comment by bduggan** [comment]
Okay, it now uses the apache archive server which has all older versions. This looks fairly permanent.
I would rather use a "latest" link that redirects to the latest one, but I couldn't find a URL like that.

**Comment by zednis** [comment]
ok, that works for me :-)

**Pull request merged**
