### PR TITLE
Clarified various definitions

### PR DESCRIPTION
**Pull request by justgo129**
I've clarified some of the definitions in the gcis ontology concerning images, figures, arrays, and tables.  @zednis, please confirm at your convenience whether they properly express their being properties in-lieu of classes, and to avoid using a word in its definition where possible and sensical.  I adapted the previously stated definitions for these assuming they reflected such issues but I'd appreciate a quick revisit of them.

### CODE REVIEW

**Comment by justgo129** [comment]
And, as a corollary, I'm a little unsure as to why the rdfs:label "has Finding" isn't "Has Finding" given the convention below.

gcis:hasAuthor a owl:ObjectProperty ;
    rdfs:label "has author" ;
    rdfs:comment "A resource may have one or more authors." ;
    rdfs:range gcis:Agent ;
    rdfs:subPropertyOf prov:wasAttributedTo .

gcis:hasFinding a owl:ObjectProperty ;
    rdfs:label "Has Finding" ;
    rdfs:comment "A publication may contain findings." ;
    rdfs:range gcis:Finding ;
    rdfs:subPropertyOf dcterms:hasPart.

gcis:hasFigure a owl:ObjectProperty ;
    rdfs:label "has figure" ;
    rdfs:comment "A publication contains one or more graphical components which most times but not necessarily are numbered and contain titles and captions ."; 
    rdfs:domain gcis:Publication ;
    rdfs:range gcis:Figure ;
    rdfs:subPropertyOf dcterms:hasPart .

**Comment by justgo129** [comment]
@zednis @xgmachina @rewolfe I'm curious as to your opinion on this one.

**Comment by zednis** [comment]
@justgo129 I made the label capitalization updates in #133 by hand, so it is possible some were missed.  i would recommend we update the label to "has finding" to be consistent with the current convention.

**Comment by justgo129** [comment]
Thanks, @zednis.  I just updated the label for "has finding."  Are we all right with the proposed clarifications to the definitions at the top of this ticket?

**Comment by zednis** [comment]
Based on their definitions, should `gcis:Publication` be in the domain of `gcis:hasFinding` and range of `gcis:isFindingOf`?

**Comment by justgo129** [comment]
@zednis, I'll defer to @bduggan about your question.

**Comment by justgo129** [comment]
@zednis what is your recommendation on the gcis:Publication matter?  My gut is "yes" but would like to confirm.

**Comment by justgo129** [comment]
Merged #144.

**Pull request merged**
