### PR TITLE
Added three properties

### PR DESCRIPTION
**Pull request by xgmachina**
Added three properties:
gcis:derivedFromScenario
gcis:derivedModelRunOutputs
gcis:contributedModel

### CODE REVIEW

**Comment by xgmachina** [comment]
Per the discussion in #12

**Comment by justgo129** [comment]
:+1: @rewolfe are we good to merge?

**Comment by rewolfe** [comment]
Sure.

On Tue, Oct 13, 2015 at 4:27 PM, justgo129 notifications@github.com wrote:

> [image: :+1:] @rewolfe https://github.com/rewolfe are we good to merge?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/159#issuecomment-147842253.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Merged #159.

**Comment by justgo129** [comment]
@zednis @xgmachina could we modify the definition for gcis:derivedModelRunOutputs at:
https://github.com/USGCRP/gcis-ontology/commit/2ec2336f499bd60c8ebbaaaf393c0602ea7a2a42 ?

I'm not sure I understand it; is the word "from" missing?  Thanks.

**Comment by zednis** [comment]
The from is not missing, the property is for the relationship from the scenario to the derived modelrun outputs.

`ex:some_scenario gcis:derivedModelRunOutputs ex:some_model_run_outputs`

**Comment by justgo129** [comment]
I'll rephrase; I don't actually understand the definition.  I think "A scenario...derived one or more model outputs outputs" reads somewhat awkwardly to me.

**Comment by zednis** [comment]
ok, I'll create a new ticket for that discussion.

**Pull request merged**
