### PR TITLE
Adding subclasses of gcis:Publication

### LINKED ISSUE #34: D3. Should we add Book, Webpage, Article, and Journal as subclasses of Publication?
Since we have gcis:Report, gcis:Image, and gcis:Figure, should we also have gcis:Book, gcis:Webpage, gcis:Article, and gcis:Journal, and make these all subclasses of their respective terms in the bibo ontology?

### PR DESCRIPTION
**Pull request by zednis**
closes #34

### CODE REVIEW

**Comment by justgo129** [comment]
@zednis , do you advise replacing "a bibo:Book" with "a gcis:Book" on line 13 at:
https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/templates/book/object.ttl.tut

**Comment by zednis** [comment]
@justgo129 perhaps.  There will be a few more classes added as part of this proposed change (Article, Journal, etc) and then we will look at impacts re: property domains and ranges.

**Comment by xgmachina** [comment]
I thought it was only a merge of changes, but it committed to the master. Added the definition of those four classes. @zednis and @justgo129 Please confirm if it is okay.

**Comment by zednis** [comment]
@xgmachina merging a pull request does commit the changes in the request to the master branch.

I am happy with what was merged and I would be ok keeping this pull request and #34 closed and to delete the feature branch.

**Comment by justgo129** [comment]
I reopened #34.

**Pull request merged**
