### PR TITLE
revisited gcis:Article and gcis:Chapter

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by zednis** [comment]
This diff looks ok.  Please verify that your fork is synced with the upstream USGCRP repo before proceeding.

https://help.github.com/articles/syncing-a-fork/

**Comment by justgo129** [comment]
Verified.

**Comment by zednis** [comment]
ok, I am happy to merge this change if it does not overlap and interfere with any of the other open pull requests.  There seems to be a LOT of overlapping changes and I want to work our way out of it without creating undue conflicts.

If you are confident that this change will not conflict with any of the other pull requests, or if we can close all the pull requests that this might interfere with, then :+1: to this pull request.

**Comment by justgo129** [comment]
I suggest this:
  I can delete most of the outstanding pull requests since they will take < 5 minutes to recommit, combined (and they were submitted by me to begin with).  They mostly involve wording and spacing.
  After I close those, we merge this one (#65).
  @zednis, please confirm that https://github.com/USGCRP/gcis-ontology/pull/56 would not be problematic in this regard.  I'm hesitant to delete one of your branches.

**Comment by zednis** [comment]
@justgo129 I think we should be ok to leave #56 open; based on the network graph it does not appear to be in a weird state and has no overlap with the other branches.

**Comment by justgo129** [comment]
Great.  I just deleted those other pull requests and branches, retaining only #54 and #56.
https://github.com/usgcrp/gcis-ontology/pulls

I can recommit the outstanding commits (in what are now closed pull requests) later since we still have a record of them in github.

We should be good to merge #65 .

**Comment by zednis** [comment]
Great.  :+1: to merge this pull request.

**Comment by justgo129** [comment]
Same here.  I'll hold off on the aforementioned recommits until after this current one (#65) is merged.

**Comment by zednis** [comment]
Do you want me to do the merge?

**Comment by justgo129** [comment]
Sure, barring any concerns by @aulenbac @bduggan or @rewolfe.

**Comment by bduggan** [comment]
I have no concerns.

**Comment by justgo129** [comment]
Seeing no objections, @zednis please merge.

**Comment by justgo129** [comment]
Closing #65 as it has been merged.

**Pull request closed without merging**
