### PR TITLE
More testing

### PR DESCRIPTION
**Pull request by bduggan**
I've added some tests that use turtle from other ontologies (stored in this git repository).
Note that some of them cannot currently be downloaded, biro, for instance, since this URL is not responding:

http://eelst.cs.unibo.it/apps/LODE/source?url=http://purl.org/spar/biro

### CODE REVIEW

**Comment by bduggan** [comment]
Also, see issue #12

**Comment by justgo129** [comment]
Merged #97.

**Comment by bduggan** [comment]
Justin -- please, do not merge until tests complete.  The travis tests were still running when you merged this.

**Comment by justgo129** [comment]
Weird, I saw that they had stopped and were successful.

On Fri, Jul 24, 2015 at 2:56 PM, Brian Duggan notifications@github.com
wrote:

> Justin -- please, do not merge until tests complete. The travis tests were
> still running when you merged this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/97#issuecomment-124630116.

## 

---

Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by justgo129** [comment]
The page for the biro ontology was down yesterday and is still down.  Could we harvest the information at: http://vocab.ox.ac.uk/biro ?  I ask because we do invoke biro in GCIS for the purposes of citations.

**Comment by zednis** [comment]
I am closing down branches that have been merged into master as 'house cleanup'.  We can always make additions in new branches.

**Pull request merged**
