### PR TITLE
update role instance qnames

### PR DESCRIPTION
**Pull request by zednis**
role instance qnames updated to conform to lowercase_separated_by_underscores convention.

references #75

### CODE REVIEW

**Comment by justgo129** [comment]
+1.  I don't think we'll need all these terms but I'm fine with the pull request.

**Comment by justgo129** [comment]
@bduggan or @rewolfe or @aulenbac  if you're all right with this, please indicate so and I will subsequently merge.  Thanks!

**Comment by bduggan** [comment]
Does it make more sense for these to come from the turtle templates?  e.g.

 http://data.globalchange.gov/role_type/convening_lead_author.thtml

I can add a field for "comment"; the rest of this information is in the database.

**Comment by zednis** [comment]
@bduggan defining the role instances in the database / instance data and removing these declarations from the ontology file is fine with me.

**Comment by justgo129** [comment]
I'm also fine with that approach.

**Comment by justgo129** [comment]
Very good.  Closed #127, and opening an issue to focus on defining the role instances in the database and removing the declarations from the ontology.

**Pull request closed without merging**
