### PR TITLE
rdfs:comment of gcis:Book and gcis:Article

### PR DESCRIPTION
**Pull request by xgmachina**
Make small updates to the rdfs:comment content of those two classes, to
cover ebook and journal article.

### CODE REVIEW

**Comment by justgo129** [comment]
I'm all right with that for book.  In GCIS, we have been restricting the use of "journal article" to portions of published academic journals.  Portions of books are still considered books.  Newspaper articles, along with magazine articles, are grouped into the "generic" category.  Do you mind revising the definition of "article" further?  Perhaps something like: "A written composition forming an independent part of an academic journal."  @aulenbac are you aware of any "Article" entity in GCIS for which this definition would be invalid?

**Comment by xgmachina** [comment]
@justgo129 how about "A written composition in prose, usually nonfiction, on a specific topic, forming an independent part of a publication, such as a journal." or "A written composition in prose, usually nonfiction, on a specific topic, forming an independent part of a journal."

**Comment by xgmachina** [comment]
Or let me add a new class called `gcis:AcademicArticle`. which is a subclass of `gcis:Article`.

**Comment by justgo129** [comment]
@xgmachina I'm very curious as to why the clauses about prose are necessary.  Do we need them in order to associate with bibo?  I don't think any instances of gcis:Article are to non-fiction, so we can take that out.
@bduggan @aulenbac which do you of the two approaches do you prefer?  I prefer the first with a more precise definition, just for simplicity given the many types of articles in our data model.

**Comment by justgo129** [comment]
@xgmachina , this page may be helpful: https://data.globalchange.gov/resources

**Comment by justgo129** [comment]
Marshall and I discussed.
See https://github.com/USGCRP/gcis-ontology/pull/63

**Comment by zednis** [comment]
Are we abandoning this branch?

**Comment by xgmachina** [comment]
If the edits in #63 can be successfully merged with master, then we can abandon this branch.

**Comment by justgo129** [comment]
@xgmachina could you try merging?

**Comment by justgo129** [comment]
Scratch that, @xgmachina .  I've done it since I was comparing that branch anyway.  
https://github.com/USGCRP/gcis-ontology/pull/65 passes the CI tests, and covers content which @xgmachina and I discussed today.
@zednis if we end up merging #65 we can then abandon this branch - I agree with @xgmachina .

**Comment by justgo129** [comment]
Deleting this branch.

**Pull request closed without merging**
