### PR TITLE
Added InstrumentType class, updated definition of Instrument.

### PR DESCRIPTION
**Pull request by zednis**
references #35.

### CODE REVIEW

**Comment by zednis** [comment]
I am not sure if `gcis:sourceInstrument`, `gcis:hasInstrument`, and or `gcis:inPlatform` should reference `gcis:Instrument` or `gcis:InstrumentType`.

For the moment they are referencing `gcis:Instrument` so they would be used with RDF instance that describe physical instruments.

**Comment by justgo129** [comment]
@rewolfe ?

**Comment by justgo129** [comment]
@zednis when you get a chance could you please resolve the conflicts, after which I'll close this ticket?  Thanks.

**Comment by zednis** [comment]
@justgo129 I have merged master into this branch and resolved the conflict.

**Comment by justgo129** [comment]
@zednis would we need to repush this due to the jena issue, or did our resolution of it automatically cause these checks to rerun, during which they failed?

**Comment by zednis** [comment]
I will need to merge the recent update to travis-ci config into the branch for it to use the new configuration in it's checks.

**Comment by zednis** [comment]
I have merged the new Travis-CI config into this branch.  CI checks should hopefully pass now...

**Comment by justgo129** [comment]
They sure do.  Merged #93.  Thanks, @zednis.

**Pull request merged**
