### PR TITLE
Deleted gcis:Article

### PR DESCRIPTION
**Pull request by justgo129**
Deleted gcis:Article, retained gcis:AcademicArticle
Related gcis:Chapter to report in-lieu of book

### CODE REVIEW

**Comment by justgo129** [comment]
Will investigate why not working.  @justgo129 and @xgmachina have signed off on potential change.

**Comment by zednis** [comment]
I believe you will want to sync your patch branch with the master branch.  If you look at the diff you will see it would remove several recent updates to the master branch.

**Comment by zednis** [comment]
@justgo129 I think the following will merge master into your branch and allow you to push an updated branch that is synced off the current master.

```
git fetch
git checkout justgo129-patch-6
git merge master
#manually resolve any conflicts that arise
git commit gcis.ttl
git push
```

Note - do not do a `git rebase` in attempting to sync the branch with master.

**Comment by zednis** [comment]
@justgo129 @xgmachina This branch was forked off the subclases-of-publication branch (which has since been merged and deleted) and not master, which is why it is causing problems.

My recommendation is to close this pull request without merging and delete this branch and to create a new branch off master to re-implement these changes.

**Comment by justgo129** [comment]
Should #65 be deleted as well before deleting this branch?

**Comment by zednis** [comment]
@justgo129 I am not sure, there have been many overlapping commits lately and I am confused about what is being changed where.

**Comment by justgo129** [comment]
Understood.  Closing this pull request, deleting the justgo129-patch-6 branch.

**Pull request closed without merging**
