### PR TITLE
isSupportedBy

### PR DESCRIPTION
**Pull request by xgmachina**
rdfs:comment "A finding is supported by or depicted in data, figures,
models, model runs, software, etc.";

### CODE REVIEW

**Comment by xgmachina** [comment]
A change per discussion in #67

**Comment by xgmachina** [comment]
@zednis Any suggestions on how to solve the conflicts in this branch?

**Comment by justgo129** [comment]
@xgmachina I advise not merging until my concerns with https://github.com/USGCRP/gcis-ontology/issues/67 are resolved.  Thanks!

**Comment by zednis** [comment]
the branch isSupportedBy was branched off gcis-ModelRun_and_gcis-ModelRunOutput which has since been merged into master.  Master has also had an update to the label of this class, but that should not cause a conflict.

The easiest solution is to close this pull request without merging, delete this branch, and try again with a new isSupportedBy-2 branch that is based on the current master branch and not an old (merged) feature branch.

**Comment by zednis** [comment]
@xgmachina I have attempted to resolve the merge conflicts with master.  If my commit on this branch resolves the conflicts please accept/close the pull request and delete the feature branch.

**Comment by xgmachina** [comment]
@zednis Thanks a lot! I just merged the commit and then deleted the branch. I will check whether the corresponding content in master and then decide whether to make another branch.

**Pull request merged**
