### PR TITLE
GCIS Ontology Version

### PR DESCRIPTION
**Pull request by justgo129**
1.2->1.32

### CODE REVIEW

**Comment by zednis** [comment]
why 1.32?

**Comment by zednis** [comment]
why is the new version 1 dot 32?

**Comment by bduggan** [comment]
The current state of gcis-ontology/gcis.ttl  corresponds to usgcrp/gcis@1.32 aka usgcrp/gcis@999aa738d5ff65fbc3a49dad0481acbf1a946a2c (which is now in [production](http://data.globalchange.gov/owl/gcis.ttl) btw)

**Comment by zednis** [comment]
Should not the ontology version be independent of the gcis code version?

**Comment by bduggan** [comment]
It's arguable...could be done that way.  It needs to be tied to a tag in a version control system and to a release, and to the turtle templates (which are in the gcis repo), so I think it simplifies things to use the same number.  It's also consistent with how we release the database schema -- there are changes to the schema, but the version is just the tag for the release of the code.  To me, it would make sense to just add an ontology version update to the gcis release scripts, keeping everything tied together in a pretty simple way.

**Comment by zednis** [comment]
I think we should update our versioning process for the ontology, but that the ontology version should be independent of the gcis source code version.  The gcis project code could evolve at a different rate and it doesn't make sense to update the ontology version in cases were the ontology has not changed but the code that is using it has.

**Comment by bduggan** [comment]
On Thursday, July  9, Stephan Zednik wrote: 

> I think we should update our versioning process for the ontology, but that the ontology version should be independent of the gcis source code version.  The gcis project code could evolve at a different rate and it doesn't make sense to update the ontology version in cases were the ontology has not changed but the code that is using it has.

In this context, I am thinking of gcis versions as versions of the
instance data (though of course there may be data updates independent of
turtle template changes, and of course not every gcis release changes the
turtle).

If there are separate version numbers, then there would still need to be a
mapping from instance data versions to ontology versions (and the release
processes for the two would still have to be coupled).

How about if we just don't update the ontology version if it hasn't changed?
Would that address your concern?  The sequence of version numbers may of course
have gaps, but that would be okay with me.

Brian

**Comment by zednis** [comment]
I would prefer to develop a logical versioning process for the ontology independent of the instance data and driven by the nature of the changes to the ontology.  It would also be worthwhile to explore how instance data that uses that ontology could reference the ontology version.

**Comment by bduggan** [comment]
If ontology versions are their own thing, is there another
element we could use to represent releases, e.g. "revision" or
'last modified' perhaps, ideally something that shows up
on the html version

```
http://data.globalchange.gov/gcis.owl
```

maybe even just a portion of the version string.

Brian

**Comment by zednis** [comment]
@bduggan There are several annotation properties available in OWL

from http://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI

> Each ontology may have an ontology IRI, which is used to identify an ontology. If an ontology has an ontology IRI, the ontology may additionally have a version IRI, which is used to identify the version of the ontology. The version IRI may be, but need not be, equal to the ontology IRI. An ontology without an ontology IRI must not contain a version IRI.
> 
> IRIs from the reserved vocabulary must not be used as an ontology IRI or a version IRI of an OWL 2 DL ontology.
> 
> The following list provides conventions for choosing ontology IRIs and version IRIs in OWL 2 ontologies. This specification provides no mechanism for enforcing these constraints across the entire Web; however, OWL 2 tools should use them to detect problems in ontologies they process.
> 
> If an ontology has an ontology IRI but no version IRI, then a different ontology with the same ontology IRI but no version IRI should not exist.
> If an ontology has both an ontology IRI and a version IRI, then a different ontology with the same ontology IRI and the same version IRI should not exist.
> All other combinations of the ontology IRI and version IRI are not required to be unique. Thus, two different ontologies may have no ontology IRI and no version IRI; similarly, an ontology containing only an ontology IRI may coexist with another ontology with the same ontology IRI and some other version IRI.
> The ontology IRI and the version IRI together identify a particular version from an ontology series — the set of all the versions of a particular ontology identified using a common ontology IRI. In each ontology series, exactly one ontology version is regarded as the current one. Structurally, a version of a particular ontology is an instance of the Ontology UML class from the structural specification. Ontology series are not represented explicitly in the structural specification of OWL 2: they exist only as a side effect of the naming conventions described in this and the following sections.

additional ontology-level version annotations

> - The owl:priorVersion annotation property specifies the IRI of a prior version of the containing ontology.
> - The owl:backwardCompatibleWith annotation property specifies the IRI of a prior version of the containing ontology that is compatible with the current version of the containing ontology.
> - The owl:incompatibleWith annotation property specifies the IRI of a prior version of the containing ontology that is incompatible with the current version of the containing ontology.

**Comment by bduggan** [comment]
Every version of the ontology would have an IRI in github if we use
the sequence of github gcis tags as versions.

**Comment by zednis** [comment]
@bdugan I think that would be a worthwhile experiment.  I believe the versionIRI can be used with `owl:import` to import a specific version of the ontology.

We could also continue to use the `owl:versionInfo` annotation; I think we should use the same github tags as a parallel versioning number could be confusing.

**Comment by aulenbac** [comment]
Let’s also add DOIs to the discussion. We have had several requests for “the” ontology’s DOI. Given the process we are discussing, how shall we tie versionIRI, versioning number and DOIs together?

**Comment by zednis** [comment]
A DOI for the ontology?  I am not sure if we need one and if we have one what it should refer to.  We certainly would not need, or want, a new DOI for each versionIRI.

**Comment by justgo129** [comment]
I will keep this open pending further discussion.

**Comment by justgo129** [comment]
I'm closing this pending further discussion, at which point we can reopen.

**Comment by justgo129** [comment]
@zednis @aulenbac @rewolfe @bduggan are there any new thoughts on this topic?

**Comment by justgo129** [comment]
@bduggan please reopen at your convenience since I feel the time is right for a resolution of this matter.  Thanks!

**Comment by bduggan** [comment]
@justgo129 you can open gcis-ontology tickets.

**Comment by justgo129** [comment]
Actually, I can't reopen; I can solely open.  The "reopen pull request" box is grayed out.

**Comment by bduggan** [comment]
It is for me too.  Hover your mouse over the box for an explanation.

**Comment by justgo129** [comment]
Ah, thanks; I didn't realize that github has that functionality.  Will open as a new ticket.

**Comment by justgo129** [comment]
Continued at:
https://github.com/USGCRP/gcis-ontology/pull/149

**Pull request closed without merging**
