### PR TITLE
added author-orcid test

### PR DESCRIPTION
**Pull request by rewolfe**

### CODE REVIEW

**Comment by zednis** [comment]
Alas, this is a pull request from your forked master so I cannot help with commits.

based on travis-CI we are almost there.  https://travis-ci.org/USGCRP/gcis-ontology/builds/91041446

```
not ok 8 - 07-author-orcid.sparql
# /tmp/errs:
# 1a2
# > http://data.globalchange.gov/person/3,Coyote,Wile E.,0000-0001-2345-6789,2
# 4d4
# < http://data.globalchange.gov/person/3,Coyote,Wile E.,0000-0001-2345-6789,1
```

We just need to change the expected output of this test so the frequency is correct.

**Comment by zednis** [comment]
FYI - if we do changes in non-master branches of this repo (as opposed to in the master branch of forked person repos) it will be easier for the group to help with commits.

**Comment by rewolfe** [comment]
Sorry, I meant to finish this Friday.  I'll finish in by 2:30.  Next time,
I'll do a non-master branch.

On Mon, Nov 16, 2015 at 1:27 PM, Stephan Zednik notifications@github.com
wrote:

> FYI - if we do changes in non-master branches of this repo (as opposed to
> in the master branch of forked person repos) it will be easier for the
> group to help with commits.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/174#issuecomment-157128025.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by rewolfe** [comment]
Output still not quite what is expected.  Will continue debugging on a branch.

**Pull request merged**
