### PR TITLE
literal comment of gcis:isSupportedBy

### PR DESCRIPTION
**Pull request by xgmachina**
updated to rdfs:comment "A finding may be supported by or depicted in a
few resources, such as data, figures, models, and software, etc."

### CODE REVIEW

**Comment by xgmachina** [comment]
This is for #67. @justgo129 Can you take a view of the updated rdfs:comment? Thanks.

**Comment by justgo129** [comment]
Sure thing, @xgmachina.  I like where this is going but I recommend something like:

"A finding is supported by resources, which may include data, figures, tables, model outputs, and/or external documents"
in-lieu of:
""A finding may be supported by or depicted in a few resources, such as data, figures, models, and software, etc.""

@rewolfe what do you think?

**Comment by rewolfe** [comment]
+1

On Wed, Sep 9, 2015 at 8:59 PM, justgo129 notifications@github.com wrote:

> Sure thing, @xgmachina https://github.com/xgmachina. I like where this
> is going but I recommend something like:
> 
> "A finding is supported by resources, which may include data, figures,
> tables, models, and/or external documents"
> in-lieu of:
> ""A finding may be supported by or depicted in a few resources, such as
> data, figures, models, and software, etc.""
> 
> @rewolfe https://github.com/rewolfe what do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/pull/150#issuecomment-139083290.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Query and expected results have also been added to the gcis-ontology repo, see:
https://github.com/USGCRP/gcis-ontology/pull/151
https://github.com/USGCRP/gcis-ontology/issues/132

**Comment by justgo129** [comment]
Merged #150.

**Pull request merged**
