### PR TITLE
updated specified version to 2.0; added owl:versionIRI

### LINKED ISSUE #149: GCIS Ontology Version
Continuation of https://github.com/USGCRP/gcis-ontology/pull/54

### PR DESCRIPTION
**Pull request by zednis**
resolves #149

### CODE REVIEW

**Comment by justgo129** [comment]
Since this request is failing, I'm closing #167.

**Comment by zednis** [comment]
@justgo129 we don't automatically close a pull request just because it is failing as additional commits can be made to the branch to correct the issue, we just don't merge the pull request unless it is passing.

**Comment by zednis** [comment]
Additionally, it looks like the 'failed test' on this commit was actually on master - which was failing tests at the time.

**Comment by justgo129** [comment]
@zednis I am absolutely fine with your suggested approach.  Please note that it differs from what the group did previously -- we closed and then reopened when problems were fixed.  I am more than happy to adopt this suggest practice.

**Comment by justgo129** [comment]
@rewolfe if you are all right with the suggested URI shown on Line 21 of the commit, I will merge.

**Comment by rewolfe** [comment]
@justgo129 - Looks good.

**Comment by justgo129** [comment]
Merged #167.

**Pull request merged**
