### PR TITLE
fixed prefix typo.  xsd:Scenario -> gcis:Scenario

### PR DESCRIPTION
**Pull request by zednis**

### CODE REVIEW

**Comment by justgo129** [comment]
I am fine with this suggestion although I'm not sure if we should restrict the range to a gcis:Report.  Right now, that approach fits our needs, but going forward could scenarios conceivably have ranges of bibo:Book or bibo:Article as well?  I'm willing to cross that bridge when it comes though.  @aulenbac what do you think?

**Comment by zednis** [comment]
@justgo129 good point.  I agree that the domains and ranges are too strict.  This original pull request was just to fix the typos, but I am amenable to increasing the scope to broaden the domain and ranges of the properties if the group can come to a consensus on a change.

**Comment by bduggan** [comment]
I agree that the domain/range need to be improved.  Scenarios are closely tied to models.  Reports may reference them, but I don't think it makes sense to build that into a data model; lots of things can reference scenarios: journals, articles, even images -- e.g. as discussed in usgcrp/gcis#175 -- RCP2.6 is a scenario related to an image.

**Comment by zednis** [comment]
proposal: 
1) remove domain from `gcis:describesScenario`
2) rename `gcis:isDescribedIn` to `gcis:scenarioDescribedIn`
2) remove range from `gcis:scenarioDescribedIn`
4) make `gcis:describesScenario` and `gcis:scenarioDescribedIn` inverse properties

**Comment by justgo129** [comment]
@zednis everything except number 2 makes sense to me.  Could you please elaborate on the need for the second one?

**Comment by zednis** [comment]
@justgo129 I think the property name `gcis:isDescribedIn` and it's label and definition are too broad for the desired usage of this property.  I believe it will likely cause confusion in the future.  Since this property is intended to be associated with scenarios, and we are talking about making it the inverse of `gcis:describesScenario`, I think a rename is appropriate.

edit:  also I think `gcis:scenarioDescribedIn` is the logical inverse name to `gcis:describesScenario`

**Comment by xgmachina** [comment]
I agree to make `gcis:describesScenario` and `gcis:scenarioDescribedIn` inverse properties.

**Comment by zednis** [comment]
Thanks @xgmachina I have split the property-change proposal into its own issue, #28, for further discussion.

**Pull request merged**
