### PR TITLE
one more grammar

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by zednis** [comment]
:+1:

**Comment by bduggan** [comment]
The grammar change is fine, so :+1:, but "the time information" is vague, and calling out a specific "observation" presumes something about the nature of the data (a trivial example would be a dataset consisting of moving averages) so I think there's room for improvement, but this issue is perhaps not the place for that discussion.

**Comment by justgo129** [comment]
I agree, @bduggan.  I suggest pulling, and in the meantime, I can initiate an issue around that broader question.

**Comment by justgo129** [comment]
Merged #43.

**Pull request merged**
